name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Read properties.proj
        id: read-properties
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Sources/Properties.proj
        
      - name: Determine semantic version from properties.
        id: get-semantic-version
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ steps.read-properties.outputs.content }}
          regex: '<Version>(.*?)</Version>'  
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: NUGET - Source
        run: nuget sources Add -Name Artifactory -Source https://silvester.jfrog.io/artifactory/api/nuget/silvester-nuget -username ${{ secrets.ARTIFACTORY_USERNAME }} -password ${{ secrets.ARTIFACTORY_PASSWORD }}
              
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
          registry: silvester.jfrog.io
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            silvester.jfrog.io/silvester-docker/pathfinder-official-web:${{ steps.get-semantic-version.outputs.group1 }}
            silvester.jfrog.io/silvester-docker/pathfinder-official-web:latest
